[package]
name = "gamecrab"
description = "A Game Boy (Color) emulator written in Rust."
repository = "https://github.com/Lokathor/gamecrab"
version = "0.0.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"





[dependencies]
